#varable precedence
#CLI level
#Task Level
#role level
#play level
#host_vars level
#inventory level
# group_vars level

- name: variable demo
  hosts: localhost
  connection: local
  vars:
    a: 100
  roles:
    - sample
  tasks:
    - name: printing variable
      ansible.builtin.debug:
        msg: a - {{ a }}
    - name: printing variable
      vars:
        a: 200
      ansible.builtin.debug:
        msg: a - {{ a }}


- name: Variable demo1
  hosts: all
  tasks:
    - name: Variable from Inventory
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Variable demo2
  hosts: all
  tasks:
    - name: Variable from Inventory vars
      ansible.builtin.debug:
        msg: URL1 - {{ URL1 }}



- name: Facts demo1
  hosts: all
  tasks:
    - name: Print a fact
      ansible.builtin.debug:
        msg: ansible_architecture - {{ ansible_architecture }}